/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/basilisk/Basilisk.gltf -r public
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";

export function Basilisk (props) {
  const { nodes, materials } = useGLTF('3DFiles//basilisk/Basilisk.gltf');
  return (
    <Canvas style={{height: '100vh',width: '100vw'}}>
      <OrbitControls />
      <ambientLight intensity={0.5}/>
      <pointLight position={[10,5,10]}/>
      <spotLight
          position={[10, 15, 10]}
          angle={0.3}
      />
      <group {...props} dispose={null}>
        <mesh geometry={nodes.Cube029.geometry} material={materials.Material} rotation={[-Math.PI, 0.46, -Math.PI]} scale={0.81} />
      </group>
    </Canvas>
  )
};

useGLTF.preload('/basilisk/Basilisk.gltf');
