/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/3Dfiles/cheshire-cat/CheshireCat.gltf -r public
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";

export function CheshireCat (props) {
  const { nodes, materials } = useGLTF('/cheshire-cat/CheshireCat.gltf')
  return (
    <Canvas style={{height: '100vh',width: '100vw'}}>
      <OrbitControls />
      <ambientLight intensity={0.5}/>
      <pointLight position={[10,5,10]}/>
      <spotLight
          position={[10, 15, 10]}
          angle={0.3}
      />
      <group {...props} dispose={null}>
        <group position={[2.17, 0, -8.72]}>
          <mesh geometry={nodes.Sphere012_1.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Sphere012_2.geometry} material={materials['Material.034']} />
          <mesh geometry={nodes.Sphere012_3.geometry} material={materials['light purple']} />
          <mesh geometry={nodes.Sphere012_4.geometry} material={materials['Dark Purple']} />
          <mesh geometry={nodes.Sphere012_5.geometry} material={materials['Material.030']} />
          <mesh geometry={nodes.Sphere012_6.geometry} material={materials['Material.032']} />
          <mesh geometry={nodes.Sphere012_7.geometry} material={materials['Material.006']} />
          <mesh geometry={nodes.Sphere012_8.geometry} material={materials['Material.024']} />
          <mesh geometry={nodes.Sphere012_9.geometry} material={materials['Material.028']} />
          <mesh geometry={nodes.Sphere012_10.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Sphere012_11.geometry} material={materials['Material.013']} />
          <mesh geometry={nodes.Sphere012_12.geometry} material={materials['Material.014']} />
          <mesh geometry={nodes.Sphere012_13.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Sphere012_14.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.Sphere012_15.geometry} material={materials['Material.023']} />
          <mesh geometry={nodes.Sphere012_16.geometry} material={materials['Material.033']} />
          <mesh geometry={nodes.Sphere012_17.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Sphere012_18.geometry} material={materials['Material.011']} />
          <mesh geometry={nodes.Sphere012_19.geometry} material={materials['Material.025']} />
          <mesh geometry={nodes.Sphere012_20.geometry} material={materials['Material.026']} />
          <mesh geometry={nodes.Sphere012_21.geometry} material={materials['Material.029']} />
        </group>
      </group>
    </Canvas>
  )
}

useGLTF.preload('/cheshire-cat/CheshireCat.gltf');
