/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/3Dfiles/elf-dagger/ElfDagger.gltf -r public
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";

export function ElfDagger (props) {
  const { nodes } = useGLTF('/elf-dagger/ElfDagger.gltf')
  return (
    <Canvas style={{height: '100vh',width: '100vw'}}>
      <OrbitControls />
      <ambientLight intensity={0.5}/>
      <pointLight position={[10,5,10]}/>
      <spotLight
          position={[10, 15, 10]}
          angle={0.3}
      />
      <group {...props} dispose={null}>
        <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} position={[0, 2.02, 0.16]} rotation={[0.35, 0, -Math.PI / 2]} scale={0.13} />
      </group>
    </Canvas>
  )
}

useGLTF.preload('/elf-dagger/ElfDagger.gltf')
