/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/3Dfiles/elf-axe/ElvenAxeAdvHoard.gltf -r public
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";

export function ElfAxe (props) {
  const { nodes } = useGLTF('/3Dfiles/elf-axe/ElvenAxeAdvHoard.gltf')
  return (
    <Canvas style={{height: '100vh',width: '100vw'}}>
      <OrbitControls />
      <ambientLight intensity={0.5}/>
      <pointLight position={[10,5,10]}/>
      <spotLight
          position={[10, 15, 10]}
          angle={0.3}
      />
      <group {...props} dispose={null}>
        <mesh geometry={nodes.Plane003.geometry} material={nodes.Plane003.material} position={[0, 10.16, 0.01]} rotation={[0, 0, -Math.PI / 2]} scale={0.63} />
      </group>
    </Canvas>
  )
}

useGLTF.preload('/3Dfiles/elf-axe/ElvenAxeAdvHoard.gltf')
