/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/3Dfiles/ganyu/Ganyu.gltf -r public
*/

import React  from 'react'
import { useGLTF } from '@react-three/drei'
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";

export function Ganyu (props) {
  const { nodes, materials } = useGLTF('3DFiles//ganyu/Ganyu.gltf')
  return (
    <Canvas style={{height: '100vh',width: '100vw'}}>
      <OrbitControls />
      <ambientLight intensity={0.5}/>
      <pointLight position={[10,5,10]}/>
      <spotLight
          position={[10, 15, 10]}
          angle={0.3}
      />
      <group {...props} dispose={null}>
        <mesh geometry={nodes.Cylinder.geometry} material={materials.Material} position={[2.92, 1.01, -5.11]} scale={1.46} />
        <group position={[2.92, -6.14, -4.83]} scale={1.46}>
          <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['Material.003']} />
        </group>
        <mesh geometry={nodes.Cylinder002.geometry} material={materials.Material} position={[2.92, -6.64, -4.83]} scale={1.46} />
        <group position={[1.54, 9.39, -4.06]} rotation={[-2.36, 0, 0]} scale={2.18}>
          <mesh geometry={nodes.Cube001.geometry} material={materials.Material} />
          <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.004']} />
        </group>
        <mesh geometry={nodes.Cube002.geometry} material={materials.Material} position={[1.98, 11.02, -15.79]} rotation={[-0.32, 0.73, 0.46]} scale={[1, 1.35, 1]} />
        <group position={[0.53, -2.35, -13.44]} rotation={[0, 0.67, -0.97]} scale={5.42}>
          <mesh geometry={nodes.Cube_1.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cube_2.geometry} material={materials['Material.001']} />
        </group>
      </group>
    </Canvas>
  )
}

useGLTF.preload('/ganyu/Ganyu.gltf')
