/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/3Dfiles/genie/Genie.gltf -r public
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";

export function Genie (props) {
  const { nodes } = useGLTF('3DFiles//genie/Genie.gltf');
  return (
    <Canvas style={{height: '100vh',width: '100vw'}}>
      <OrbitControls />
      <ambientLight intensity={0.5}/>
      <pointLight position={[10,5,10]}/>
      <spotLight
          position={[10, 15, 10]}
          angle={0.3}
      />
      <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere002.geometry} material={nodes.Sphere002.material} rotation={[-0.09, -0.85, 0.26]} scale={0.44} />
      </group>
    </Canvas>
  )
};

useGLTF.preload('/genie/Genie.gltf');
