/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/3Dfiles/gremlin/Gremlin.gltf -r public
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";

export function Gremlin (props) {
  const { nodes } = useGLTF('/gremlin/Gremlin.gltf')
  return (
    <Canvas style={{height: '100vh',width: '100vw'}}>
      <OrbitControls />
      <ambientLight intensity={0.5}/>
      <pointLight position={[10,5,10]}/>
      <spotLight
          position={[10, 15, 10]}
          angle={0.3}
      />
      <group {...props} dispose={null}>
        <mesh geometry={nodes.Cube008.geometry} material={nodes.Cube008.material} position={[-0.09, 3.81, 2.02]} rotation={[0.14, 0.17, -1.19]} scale={[0.15, 0.28, 0.22]} />
      </group>
    </Canvas>
  )
};

useGLTF.preload('/gremlin/Gremlin.gltf');
