/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/3Dfiles/lizardman/Lizardman.gltf -r public
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";

export function Lizardman (props) {
  const { nodes } = useGLTF('3DFiles//lizardman/Lizardman.gltf');
  return (
    <Canvas style={{height: '100vh',width: '100vw'}}>
      <OrbitControls />
      <ambientLight intensity={0.5}/>
      <pointLight position={[10,5,10]}/>
      <spotLight
          position={[10, 15, 10]}
          angle={0.3}
      />
      <group {...props} dispose={null}>
        <mesh geometry={nodes.Cylinder068.geometry} material={nodes.Cylinder068.material} rotation={[-1.05, -0.54, -0.68]} scale={0.13} />
      </group>
    </Canvas>
  )
};

useGLTF.preload('/lizardman/Lizardman.gltf');
