/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/3Dfiles/mech-pistol/MechPistol.gltf -r public
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";

export function MechPistol (props) {
  const { nodes, materials } = useGLTF('3DFiles//mech-pistol/MechPistol.gltf');
  return (
    <Canvas style={{height: '100vh',width: '100vw'}}>
      <OrbitControls />
      <ambientLight intensity={0.5}/>
      <pointLight position={[10,5,10]}/>
      <spotLight
          position={[10, 15, 10]}
          angle={0.3}
      />
      <group {...props} dispose={null}>
        <group rotation={[0.44, 0, 0]} scale={0.25}>
          <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cube001_2.geometry} material={materials.Material} />
          <mesh geometry={nodes.Cube001_3.geometry} material={materials['Material.004']} />
        </group>
      </group>
    </Canvas>
  )
};

useGLTF.preload('/mech-pistol/MechPistol.gltf');
