/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/3Dfiles/naga/Naga.gltf -r public
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";

export function Naga (props) {
  const { nodes, materials } = useGLTF('/3Dfiles/naga/Naga.gltf');
  return (
    <Canvas style={{height: '100vh',width: '100vw'}}>
      <OrbitControls />
      <ambientLight intensity={0.1}/>
      <pointLight position={[10,5,10]}/>
      <spotLight
          position={[10, 15, 10]}
          angle={0.3}
      />
      <group {...props} dispose={null}>
        <group rotation={[2.98, -0.16, 1.35]} scale={0.81}>
          <mesh geometry={nodes.Cylinder167_1.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cylinder167_2.geometry} material={materials.Material} />
          <mesh geometry={nodes.Cylinder167_3.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Cylinder167_4.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.Cylinder167_5.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Cylinder167_6.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cylinder167_7.geometry} material={materials['Material.006']} />
          <mesh geometry={nodes.Cylinder167_8.geometry} material={materials['Material.007']} />
        </group>
      </group>
    </Canvas>
  )
};

useGLTF.preload('/3Dfiles/naga/Naga.gltf');
