/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/3Dfiles/oni/Oni.gltf -r public
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";

export function Oni (props) {
  const { nodes } = useGLTF('3DFiles//oni/Oni.gltf')
  return (
    <Canvas style={{height: '100vh',width: '100vw'}}>
      <OrbitControls />
      <ambientLight intensity={0.5}/>
      <pointLight position={[10,5,10]}/>
      <spotLight
          position={[10, 15, 10]}
          angle={0.3}
      />
      <group {...props} dispose={null}>
        <mesh geometry={nodes.Cylinder004.geometry} material={nodes.Cylinder004.material} rotation={[0.89, 0.22, -0.33]} scale={0.94} />
      </group>
    </Canvas>
  )
}

useGLTF.preload('/oni/Oni.gltf')
