/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/3Dfiles/raziel/Raziel.gltf -r public
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";

export function Raziel (props) {
  const { nodes} = useGLTF('/3Dfiles/raziel/Raziel.gltf')
  return (
    <Canvas style={{height: '100vh',width: '100vw'}}>
      <OrbitControls />
      <ambientLight intensity={0.5}/>
      <pointLight position={[10,5,10]}/>
      <spotLight
          position={[10, 15, 10]}
          angle={0.3}
      />
      <group {...props} dispose={null}>
        <mesh geometry={nodes.Cube010.geometry} material={nodes.Cube010.material} position={[-4.22, 18.45, -15.3]} rotation={[0, 0.34, -0.36]} scale={0.57} />
      </group>
    </Canvas>
  )
};

useGLTF.preload('/3Dfiles/raziel/Raziel.gltf');
