/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/3Dfiles/sarenrae/Sarenrae.gltf -r public
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";

export function Sarenrae (props) {
  const { nodes } = useGLTF('/3Dfiles/sarenrae/Sarenrae.gltf')
  return (
    <Canvas style={{height: '100vh',width: '100vw'}}>
      <OrbitControls />
      <ambientLight intensity={0.5}/>
      <pointLight position={[10,5,10]}/>
      <spotLight
          position={[10, 15, 10]}
          angle={0.3}
      />
      <group {...props} dispose={null}>
        <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[3, 0, 0.49]} />
        <mesh geometry={nodes.Plane004.geometry} material={nodes.Plane004.material} position={[-3, -2, 4]} rotation={[-0.05, 0, 0]} />
      </group>
      </Canvas>
  )
}

useGLTF.preload('/3Dfiles/sarenrae/Sarenrae.gltf')
