/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/3Dfiles/serpent-fly/SerpentFly.gltf -r public
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";

export function SerpentFly (props) {
  const { nodes, materials } = useGLTF('/serpent-fly/SerpentFly.gltf')
  return (
    <Canvas style={{height: '100vh',width: '100vw'}}>
      <OrbitControls />
      <ambientLight intensity={0.5}/>
      <pointLight position={[10,5,10]}/>
      <spotLight
          position={[10, 15, 10]}
          angle={0.3}
      />
      <group {...props} dispose={null}>
        <group position={[-3.64, 0, 1.74]} rotation={[-0.38, 0.07, -1.54]}>
          <mesh geometry={nodes.Plane001.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Plane001_1.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Plane001_2.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Plane001_3.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.Plane001_4.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Plane001_5.geometry} material={materials.Material} />
          <mesh geometry={nodes.Plane001_6.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Plane001_7.geometry} material={materials['Material.011']} />
          <mesh geometry={nodes.Plane001_8.geometry} material={materials['Material.012']} />
          <mesh geometry={nodes.Plane001_9.geometry} material={materials['Material.010']} />
        </group>
      </group>
    </Canvas>
  )
};

useGLTF.preload('/serpent-fly/SerpentFly.gltf');
