/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/3Dfiles/wishes/Wishes.gltf -r public
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";

export function Wishes (props) {
  const { nodes } = useGLTF('3DFiles//wishes/Wishes.gltf');
  return (
    <Canvas style={{height: '100vh',width: '100vw'}}>
      <OrbitControls />
      <ambientLight intensity={0.5}/>
      <pointLight position={[10,5,10]}/>
      <spotLight
          position={[10, 15, 10]}
          angle={0.3}
      />
      <group {...props} dispose={null}>
        <mesh geometry={nodes.Icosphere002.geometry} material={nodes.Icosphere002.material} rotation={[1.41, 0.68, -0.92]} scale={[0.14, 0.18, 0.13]} />
      </group>
    </Canvas>
  )
};

useGLTF.preload('/wishes/Wishes.gltf');
